replicaCount: 1

image:
  repository: 28081989/node-hello-world
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: ""
  annotations: {}
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: node-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific






